export const roomData = [
  {
    id: 1,
    name: "Double Room",
    description:
      "facilisis tempor erat facilisis. Proin imperdiet rutrum cursus",
    longDescription:
      "Experience the perfect blend of comfort and elegance in our spacious Double Room. Designed for relaxation, this room features premium bedding, modern amenities, and a serene atmosphere that ensures a restful stay. The thoughtfully arranged space includes a comfortable seating area where you can unwind after a day of exploration or business meetings.",
    price: 219,
    image: "/hotel-2.webp",
    beds: 3,
    guests: 4,
    rating: 4.9,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat-screen TV",
      "Mini Bar",
      "Coffee Maker",
      "In-room Safe",
      "Private Bathroom",
      "Hair Dryer",
      "Room Service",
    ],
  },
  {
    id: 2,
    name: "Small Suite",
    description:
      "facilisis tempor erat facilisis. Proin imperdiet rutrum cursus",
    longDescription:
      "Our Small Suite offers an intimate yet luxurious space for travelers seeking both comfort and style. The suite features a cozy bedroom area and a separate sitting space, allowing you to relax or work with ease. The elegant décor and premium furnishings create a welcoming atmosphere that makes you feel right at home.",
    price: 199,
    image: "/hotel-2.webp",
    beds: 2,
    guests: 3,
    rating: 4.4,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat-screen TV",
      "Mini Bar",
      "Coffee Maker",
      "In-room Safe",
      "Private Bathroom",
      "Hair Dryer",
      "Work Desk",
    ],
  },
  {
    id: 3,
    name: "Luxury Room",
    description:
      "facilisis tempor erat facilisis. Proin imperdiet rutrum cursus",
    longDescription:
      "Indulge in the ultimate luxury experience in our premium Luxury Room. This spacious accommodation features high-end furnishings, plush bedding, and an elegant design that exudes sophistication. The room offers panoramic views and is equipped with state-of-the-art amenities to ensure your stay is nothing short of extraordinary.",
    price: 305,
    image: "/hotel-2.webp",
    beds: 3,
    guests: 6,
    rating: 4.8,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Smart TV",
      "Premium Mini Bar",
      "Espresso Machine",
      "In-room Safe",
      "Luxury Bathroom",
      "Bathrobe & Slippers",
      "24/7 Room Service",
      "Turn-down Service",
      "Lounge Access",
    ],
  },
  {
    id: 4,
    name: "Junior Suite",
    description:
      "facilisis tempor erat facilisis. Proin imperdiet rutrum cursus",
    longDescription:
      "Our Junior Suite offers a perfect balance of space and comfort for both leisure and business travelers. The open-plan design features a bedroom area and a living space, providing you with ample room to relax or work. The contemporary décor and thoughtful amenities ensure a pleasant and productive stay.",
    price: 259,
    image: "/hotel-2.webp",
    beds: 4,
    guests: 2,
    rating: 3.9,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Flat-screen TV",
      "Mini Bar",
      "Coffee Maker",
      "In-room Safe",
      "Private Bathroom",
      "Hair Dryer",
      "Work Desk",
      "Sitting Area",
    ],
  },
  {
    id: 5,
    name: "Superior Room",
    description:
      "facilisis tempor erat facilisis. Proin imperdiet rutrum cursus",
    longDescription:
      "Elevate your stay in our Superior Room, where comfort meets elegance. This well-appointed room features premium furnishings, a plush king-size bed, and a range of modern amenities designed to enhance your experience. The spacious layout and sophisticated design create a tranquil retreat for discerning travelers.",
    price: 420,
    image: "/hotel-2.webp",
    beds: 3,
    guests: 7,
    rating: 2.9,
    amenities: [
      "Free Wi-Fi",
      "Air Conditioning",
      "Smart TV",
      "Mini Bar",
      "Coffee & Tea Facilities",
      "In-room Safe",
      "Luxury Bathroom",
      "Hair Dryer",
      "Work Desk",
      "Blackout Curtains",
      "Evening Turndown",
    ],
  },
];
